"use client";
import "../assets/css/base.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect, useRef, useState } from "react";
import Preloader from "@/components/loaders/Preloader";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  const [loading, setLoading] = useState(true);

  // useEffect(() => {
  //   // Simulate a delay before hiding the preloader
  //   setTimeout(() => {
  //     setLoading(false);
  //   }, 6000);
  // }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {
          loading ?
          <Preloader/>
          :
          <main data-scroll-container className="container">
          <div>{children}</div>
        </main>

        } */}
{/* <Preloader/> */}
<main data-scroll-container >
          <div>{children}</div>
        </main>
        
      </body>
    </html>
  );
}
