/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bensimulator2 (https://sketchfab.com/bensimulator1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halo-infinite-master-chief-rigged-walk-2ab775a1c67141d9a03bb5c92c115b36
Title: Halo-Infinite-Master-Chief-rigged-walk.
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Man(props) {
    
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("https://nightdistrict.thewebtestlink.xyz/webgl/man.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    //somehow trigger useGLTF and useAnimations to load the new animation HERE using animationFileToPlay
    
      actions.Walk.play()
    }, [])
 console.log(animations);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.925}
        >
          <group
            name="Master_Chief-walkfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Jupiter_Body}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Jupiter_Body_0}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.Jupiter_FaceAcc}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Object_9" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="M_MED_Jupiter" rotation={[-Math.PI / 2, 0, 0]} />
                  <group
                    name="M_MED_Jupiter_Helmet"
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("https://nightdistrict.thewebtestlink.xyz/webgl/man.glb");
